// Code generated by hero.
// source: D:\GoProjects\github.com/anden007/dp_clean_core\Backend\template\api.tpl
// DO NOT EDIT!
package template

import "bytes"

func Api(apiName string, apiPath string, vueName string, buffer *bytes.Buffer) {
	buffer.WriteString(`
// 统一请求路径前缀在libs/axios.js中添加
// import { getRequest, postRequest, deleteRequest } from '@/libs/axios';

// `)
	buffer.WriteString(apiName)
	buffer.WriteString(`分页获取数据
export const get`)
	buffer.WriteString(apiName)
	buffer.WriteString(`List = (params) => {
    return postBodyRequest('`)
	buffer.WriteString(apiPath)
	buffer.WriteString(`/getByCondition', params)
}
// `)
	buffer.WriteString(apiName)
	buffer.WriteString(`添加
export const add`)
	buffer.WriteString(apiName)
	buffer.WriteString(` = (params) => {
    return postBodyRequest('`)
	buffer.WriteString(apiPath)
	buffer.WriteString(`/add', params)
}
// `)
	buffer.WriteString(apiName)
	buffer.WriteString(`编辑
export const edit`)
	buffer.WriteString(apiName)
	buffer.WriteString(` = (params) => {
    return postBodyRequest('`)
	buffer.WriteString(apiPath)
	buffer.WriteString(`/edit', params)
}
// `)
	buffer.WriteString(apiName)
	buffer.WriteString(`删除
export const delete`)
	buffer.WriteString(apiName)
	buffer.WriteString(` = (params) => {
    return postRequest('`)
	buffer.WriteString(apiPath)
	buffer.WriteString(`/delByIds', params)
}`)

}
